### ISSUE TITLE
add a new bugzilla keyword to surface startup crash 

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman#2]

**Comment by sylvestre** [comment]
@marco-c @calixteman 
maybe we should add an autonag rule to monitor this?

**Comment by calixteman** [comment]
Sure.
There is a flag in crash reports:
https://crash-stats.mozilla.org/search/?startup_crash=__true__&product=Firefox&date=%3E%3D2021-11-25T10%3A24%3A00.000Z&date=%3C2021-12-02T10%3A24%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

A plan:
 - get bugs with signatures
 - check if crashes for a given signature have the flag set to true
 - if the ratio number_of_crashes_with_flag_true over number_of_crashes is greater than a threshold then add the flag in bugzilla.

1. What could be a good threshold ?

FYI, in crash-stop we have something to show that a crash is a startup crash (see cells in red):
https://bugzilla.mozilla.org/show_bug.cgi?id=1471720
The threshold is 50%:
https://github.com/mozilla/crash-stop-addon/blob/7d2a8054dca38d4a4cdf247487c0418137d38217/templates/sumup.html#L91

2. How to deal with bugs with multiple signatures ?

**Comment by marco-c** [comment]
I had filed a issue on autonag, https://github.com/mozilla/relman-auto-nag/issues/1162.
Pascal was going to look into it.
